routes/web.php
<?php

use App\Http\Controllers\StudentController;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TrainingController;
use App\Http\Controllers\TrainingStudentController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\HourController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\KDController;
use App\Http\Controllers\FileController;
use App\Http\Controllers\InternshipController;
use App\Http\Controllers\InternshiphoursController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::group(['middleware' => ['auth']], function () {

    Route::resource('students', StudentController::class)->only(['index']); //users without the role teacher can only see the INDEX view

    Route::group(['middleware' => ['teacher']], function () { //users with the teacher role have acces to
        Route::resource('trainings', TrainingController::class)->except(['index','show']); //complete resource of trianings
        Route::resource('students', StudentController::class)->except(['index']); //complete resource of student

    });
    Route::resource('trainings', TrainingController::class)->only(['index','show']); //users without the role teacher can only see the INDEX view

    Route::resources([
        'hours' => HourController::class,
        'trainings.student' => TrainingStudentController::class,
        'internship_hours' => \App\Http\Controllers\InternshiphoursController::class,
        'teachers' => TeacherController::class,
        'companies' => \App\Http\Controllers\CompanyController::class,
        'KD' => KDController::class,
    ]);
    Route::get('school-company', [UserController::class, 'index'])->name('school.company');

    Route::get('show-hours', [HourController::class, 'show'])->name('hours.show');

    Route::get('/company/{company}/request', [InternshipController::class, 'request']);
    Route::get('/company/requests', [InternshipController::class, 'studentsRequests']);
    Route::post('/company/{company}/request', [InternshipController::class, 'requestPost']);

    Route::group(['prefix' => 'my-company'], function () {
        Route::get('requests', [InternshipController::class, 'requests']);
        //Todo:: improve these routes
        Route::get('requests/edit/{internship}', [InternshipController::class, 'edit']);
        Route::post('requests/edit/{internship}', [InternshipController::class, 'update']);
        Route::get('requests/deny/{internship}', [InternshipController::class, 'denyRequest']);
        Route::get('requests/accept/{internship}', [InternshipController::class, 'acceptRequest']);

        Route::get('stagaires', [InternshipController::class, 'stagaires']);
    });


    Route::get('create-company', [TeacherController::class, 'createcompanypage']);
    Route::get('change-company', [TeacherController::class, 'changecompanypage']);
    Route::get('change-hours{id}', [HourController::class, 'edit'])->name('change.hours');
    Route::get('delete-hours{id}', [HourController::class, 'destroy'])->name('delete.hours');
    Route::get('good-hours{id}', [InternshiphoursController::class, 'create'])->name('good.hours');
    Route::get('bad-hours{id}', [HourController::class, 'deny'])->name('bad.hours');
    Route::get('hours.update{id}', [HourController::class, 'update'])->name('hours.update');
    Route::get('created-company', [TeacherController::class, 'createcompany'])->name('create.company');
    Route::get('/changed-company{id}', [TeacherController::class, 'changecompany'])->name('change.company');
    Route::get('/delete-company/{id}', [TeacherController::class, 'deletecompany'])->name('delete.company');

    Route::get('/students/{student}/delete', [StudentController::class, 'delete']);
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/private/{file?}', 'FileController@get')->where('file', '(.*)');

    Route::get('/KD.showStudentKD', [App\Http\Controllers\KDController::class, 'showStudentKD']);

    Route::get('/profile', [App\Http\Controllers\ProfileController::class, 'show']);
    Route::post('/profile', [App\Http\Controllers\ProfileController::class, 'update']);

    Route::post('/update-password', [App\Http\Controllers\ProfileController::class, 'updatePassword']);
    Route::post('/send-mail', [App\Http\Controllers\MailController::class, 'store']);
    Route::post('/update-avatar', [App\Http\Controllers\ProfileController::class, 'updateAvatar']);
    Route::post('/update-adres', [App\Http\Controllers\ProfileController::class, 'updateAdres']);
});

app/Models/Hour.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Hour extends Model
{
    use HasFactory;

    static $defaultAnswer = 'Unclear';

    static $answers = [
        0 => 'Accepted',
        1 => 'Denied',
        2 => 'Unclear'
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'userid');
    }

    public function company()
    {
        return $this->belongsTo(User::class, 'intern_id')->where('type','=','bpv');
    }

    public function internship()
    {
        return $this->belongsTo(Internship::class, 'intern_id', 'id');
    }
}

app/Http/Controllers/HourController.php
<?php

namespace App\Http\Controllers;

use App\Models\Hour;
use App\Models\Internship;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class HourController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        if ($user->type == 'bpv') {
            $hour = Hour::all();
            $users = User::where('type','student')->get();
            return view('hours/bpv-hourslist', compact('hour'), compact('users'));
        }
        if ($user->type == 'student') {
            $id = $user->id;
            $hour = Hour::where('userid',$id)->get();
            return view('hours/student-hourslist', compact('hour'));
        }
        if ($user->type == 'teacher') {
            return back();
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $user = Auth::user();
        if ($user->type == 'student') {
            $id = $user->id;
            $hour = new Hour;

            $hour->intern_id = $request->intern_id;
            $hour->hours = $request->uren;
            $hour->date = $request->datum;
            $hour->begintime = $request->begintijd;
            $hour->endtime = $request->eindtijd;
            $hour->userid = $id;

            $hour->save();
            return redirect(route('hours.index'));
        }
        if ($user->type == 'bpv') {
            $hour = new Hour;

            $companyid = $user->id;
            $userid = $request->user_name;


            $internship = Internship::where('company_id', $companyid)->where('user_id', $userid)->first();

            $hour->intern_id = $internship->id;
            $hour->hours = $request->uren;
            $hour->date = $request->datum;
            $hour->begintime = $request->begintijd;
            $hour->endtime = $request->eindtijd;

            $hour->userid = $userid;

            $hour->save();

            return redirect(route('hours.index'));
        }

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Hour  $hour
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        $user = Auth::user();
        if ($user->type == 'student') {
            $users = User::where('type','bpv')->get();
            return view('hours/create-hours', compact('users'));
        }
        if ($user->type == 'bpv') {
            $users = User::where('type','student')->get();
            return view('hours/create-hours-bpv', compact('users'));
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Hour  $hour
     * @return \Illuminate\Http\Response
     */
    public function edit(Hour $hour, $id)
    {
        $user = Auth::user();
        $hour = Hour::where('id',$id)->get();
        $users = User::where('type','bpv')->get();
        if ($user->type == 'student') return view('hours/change-hours', compact('hour'), compact('users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Hour  $hour
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Hour $hour, $id)
    {
        $user = Auth::user();
        $userid = $user->id;

        $hour = Hour::find($id);

        $hour->intern_id = $request->intern_id;
        $hour->hours = $request->uren;
        $hour->date = $request->datum;
        $hour->begintime = $request->begintijd;
        $hour->endtime = $request->eindtijd;
        $hour->userid = $userid;

        $hour->save();

        return redirect(route('hours.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Hour  $hour
     * @return \Illuminate\Http\Response
     */
    public function destroy(Hour $hour, $id)
    {
        $hour = Hour::find($id);
        $hour->delete();
        return redirect(route('hours.index'));
    }

    /**
     * deny
     *
     * @return \Illuminate\Http\Response
     */
    public function deny($id)
    {
        $hour = Hour::find($id);
        $hour->status = 'Denied';
        $hour->save();
        return redirect(route('hours.index', compact('id')));
    }
}

resources/views/hours/bpv-hourslist.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="yoo-uikits-heading d-flex justify-content-between">
            <h2 class="yoo-uikits-title">Urenlijst van alle studenten</h2>
            <a class="btn btn-primary" href="{{ route('hours.show') }}">voeg data toe</a>
        </div>
        <div class="yoo-height-b30 yoo-height-lg-b30"></div>
    </div>

    <div class="container">
        <div class="yoo-card yoo-style1">
                <div class="yoo-card-body">
                    <div class="yoo-padd-lr-20">
                        <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                        <table class="table">
                            <thead>
                            <tr>
                                <th>gebruikers</th>
                                <th>email</th>
                                <th>uren</th>
                                <th>datum</th>
                                <th>begintijd</th>
                                <th>eindtijd</th>
                                <th>stage</th>
                                <th>status</th>
                                <th></th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($hour as $hours)
                            <tr>
                                <td>{{$hours->user->first_name. ' ' .$hours->user->last_name}}</td>
                                <td>{{$hours->user->email}}</td>
                                <td>{{$hours->hours}}</td>
                                <td>{{explode(' ', $hours->date)[0]}}</td>
                                <td>{{$hours->begintime}}</td>
                                <td>{{$hours->endtime}}</td>
                                <td>{{$hours->internship->Company->company_name}}</td>
                                <td>{{$hours->status}}</td {{$user = \Illuminate\Support\Facades\Auth::user()}}>
                                @if($user->id == $hours->internship->Company->id)
                                <td>
                                    <a href="good-hours{{$hours->id}}">
                                        <button class="btn-sm btn-success">
                                            klopt
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="bad-hours{{$hours->id}}">
                                        <button type="submit" class="btn-sm btn-danger">
                                            fout
                                        </button>
                                    </a>
                                </td>
                                @else
                                    <td></td>
                                    <td></td>
                                @endif
                            </tr
                                @endforeach
                            </tbody>
                        </table>
                        <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                    </div>
                </div>
                <hr>
                <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                <div class="yoo-profile-btn-group yoo-style1">
                </div>
        </div>
    </div>

@endsection

resources/views/hours/change-hours.blade.php
@extends('layouts.app')

@section('content')
    @foreach ($hour as $hours)
    <form action="{{ url('hours.update'.$hours->id) }}" method="POST">
        @endforeach
        @csrf
        @method('get')
        <input type="hidden" name="type" value="bpv" id="register_type">
        <div class="row" style="margin-top: 20px;">
            <div class="col-lg-12">
                <div class="form-group level-up form-group-md">
                    <label for="company_name">Uren</label>
                    <input type="text" class="form-control" name="uren" id="uren" {{$uren = $hours->hours}} value="{{$uren}}">
                </div>
                @error('hours')
                <div class="alert alert-danger" role="alert">
                    {{ $message }}
                </div>
                @enderror
            </div>
            <div class="col-lg-12">
                <div class="form-group level-up form-group-md">
                    <label for="email">Datum</label>
                    <input type="date" class="form-control" name="datum" id="datum" {{$datum = $hours->date}} value="{{explode(' ', $datum)[0]}}">
                </div>
                @error('datum')
                <div class="alert alert-danger" role="alert">
                    {{ $message }}
                </div>
                @enderror
            </div>
            <div class="col-lg-12">
                <div class="form-group level-up form-group-md">
                    <label for="email">Begintijd</label>
                    <input type="time" class="form-control" name="begintijd" id="begintijd" {{$begintijd = $hours->begintime}} value="{{$begintijd}}">
                </div>
                @error('begintijd')
                <div class="alert alert-danger" role="alert">
                    {{ $message }}
                </div>
                @enderror
            </div>
            <div class="col-lg-12">
                <div class="form-group level-up form-group-md">
                    <label for="email">Eindtijd</label>
                    <input type="time" class="form-control" name="eindtijd" id="eindtijd" {{$eindtijd = $hours->endtime}} value="{{$eindtijd}}">
                </div>
                @error('eindtijd')
                <div class="alert alert-danger" role="alert">
                    {{ $message }}
                </div>
                @enderror
            </div>
            <div class="col-lg-12">
                <div class="form-group level-up form-group-md">
                    <select name="intern_id" id="intern_id">
                        @foreach(Auth()->user()->Internships->where('status', 'accepted') as $internship )
                            <option  value="{{ $internship->id }}">{{ $internship->Company->company_name }}</option>
                        @endforeach
                    </select>
                </div>
                @error('company_name')
                <div class="alert alert-danger" role="alert">
                    {{ $message }}
                </div>
                @enderror
            </div>
        </div>
        <button type="submit" class="yoo-form-btn yoo-style1 yoo-color1"><span>pas uur aan</span></button>
    </form>
@endsection

resources/views/hours/create-hours-bpv.blade.php
@extends('layouts.app')

@section('content')
    <form action="{{ route('hours.create') }}" method="POST">
        @csrf
        @method('get')
        <input type="hidden" name="type" value="bpv" id="register_type">
        <div class="row" style="margin-top: 20px;">
            <div class="col-lg-12">
                <div class="form-group level-up form-group-md">
                    <select name="user_name" id="user_name">
                        @foreach($users as $user )
                            <option value="{{$user->id}}">{{ $user->first_name. " " . $user->email}}</option>
                        @endforeach
                    </select>
                </div>
                @error('uuid')
                <div class="alert alert-danger" role="alert">
                    {{ $message }}
                </div>
                @enderror
            </div>
            <div class="col-lg-12">
                <div class="form-group level-up form-group-md">
                    <label for="company_name">Uren</label>
                    <input type="text" class="form-control" name="uren" id="uren">
                </div>
                @error('hours')
                <div class="alert alert-danger" role="alert">
                    {{ $message }}
                </div>
                @enderror
            </div>
            <div class="col-lg-12">
                <div class="form-group level-up form-group-md">
                    <label for="email">Datum</label>
                    <input type="date" class="form-control" name="datum" id="datum">
                </div>
                @error('datum')
                <div class="alert alert-danger" role="alert">
                    {{ $message }}
                </div>
                @enderror
            </div>
            <div class="col-lg-12">
                <div class="form-group level-up form-group-md">
                    <label for="email">Begintijd</label>
                    <input type="time" class="form-control" name="begintijd" id="begintijd">
                </div>
                @error('begintijd')
                <div class="alert alert-danger" role="alert">
                    {{ $message }}
                </div>
                @enderror
            </div>
            <div class="col-lg-12">
                <div class="form-group level-up form-group-md">
                    <label for="email">Eindtijd</label>
                    <input type="time" class="form-control" name="eindtijd" id="eindtijd">
                </div>
                @error('eindtijd')
                <div class="alert alert-danger" role="alert">
                    {{ $message }}
                </div>
                @enderror
            </div>
        </div>
        <button type="submit" class="yoo-form-btn yoo-style1 yoo-color1"><span>Maak nieuw uur aan</span></button>
    </form>
@endsection

resources/views/hours/create-hours.blade.php
@extends('layouts.app')

@section('content')
    <form action="{{ route('hours.create') }}" method="POST">
        @csrf
        @method('get')
        <input type="hidden" name="type" value="bpv" id="register_type">
        <div class="row" style="margin-top: 20px;">
            <div class="col-lg-12">
                <div class="form-group level-up form-group-md">
                    <label for="company_name">Uren</label>
                    <input type="text" class="form-control" name="uren" id="uren">
                </div>
                @error('hours')
                <div class="alert alert-danger" role="alert">
                    {{ $message }}
                </div>
                @enderror
            </div>
            <div class="col-lg-12">
                <div class="form-group level-up form-group-md">
                    <label for="email">Datum</label>
                    <input type="date" class="form-control" name="datum" id="datum">
                </div>
                @error('datum')
                <div class="alert alert-danger" role="alert">
                    {{ $message }}
                </div>
                @enderror
            </div>
            <div class="col-lg-12">
                <div class="form-group level-up form-group-md">
                    <label for="email">Begintijd</label>
                    <input type="time" class="form-control" name="begintijd" id="begintijd">
                </div>
                @error('begintijd')
                <div class="alert alert-danger" role="alert">
                    {{ $message }}
                </div>
                @enderror
            </div>
            <div class="col-lg-12">
                <div class="form-group level-up form-group-md">
                    <label for="email">Eindtijd</label>
                    <input type="time" class="form-control" name="eindtijd" id="eindtijd">
                </div>
                @error('eindtijd')
                <div class="alert alert-danger" role="alert">
                    {{ $message }}
                </div>
                @enderror
            </div>
            <div class="col-lg-12">

                <div class="form-group level-up form-group-md">
                    <select name="intern_id" id="intern_id">
                        @foreach(Auth()->user()->Internships->where('status', 'accepted') as $internship )
                            <option  value="{{ $internship->id }}">{{ $internship->Company->company_name }}</option>
                        @endforeach
                    </select>
                </div>

                @error('company_name')
                <div class="alert alert-danger" role="alert">
                    {{ $message }}
                </div>
                @enderror
            </div>
        </div>
        <button type="submit" class="yoo-form-btn yoo-style1 yoo-color1"><span>Maak nieuw uur aan</span></button>
    </form>
@endsection

resources/views/hours/student-hourslist.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="yoo-uikits-heading d-flex justify-content-between">
            <h2 class="yoo-uikits-title">Urenlijst</h2>
            <a class="btn btn-primary" href="{{ route('hours.show') }}">voeg data toe</a>
        </div>
        <div class="yoo-height-b30 yoo-height-lg-b30"></div>
    </div>

    <div class="container">
        <div class="yoo-card yoo-style1">
                <div class="yoo-card-body">
                    <div class="yoo-padd-lr-20">
                        <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Uren</th>
                                <th>datum</th>
                                <th>begintijd</th>
                                <th>eindtijd</th>
                                <th>stage</th>
                                <th>status</th>
                                <th>acties</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($hour as $hours)
                            <tr>
                                <td>{{$hours->hours}}</td>
                                <td>{{explode(' ', $hours->date)[0]}}</td>
                                <td>{{$hours->begintime}}</td>
                                <td>{{$hours->endtime}}</td>
                                <td>{{$hours->internship->Company->company_name}}</td>
                                <td>{{$hours->status}}</td>
                                @if($hours->status == 'Unclear')
                                <td>
                                    <a href="change-hours{{$hours->id}}">
                                        <button class="btn-sm btn-primary">
                                            <ion-icon name="create-outline"></ion-icon>
                                        </button>
                                    </a>
                                    <a href="delete-hours{{$hours->id}}">
                                        <button type="submit" class="btn-sm btn-danger">
                                            <ion-icon name="trash-outline"></ion-icon>
                                        </button>
                                    </a>
                                </td>
                                @else
                                    <td></td>
                                    <td></td>
                                @endif
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                    </div>
                </div>
                <hr>
                <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                <div class="yoo-profile-btn-group yoo-style1">
                </div>
        </div>
    </div>

@endsection