routes/web.php
<?php

use App\Http\Controllers\StudentController;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TrainingController;
use App\Http\Controllers\TrainingStudentController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\HourController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\KDController;
use App\Http\Controllers\FileController;
use App\Http\Controllers\InternshipController;
use App\Http\Controllers\InternshiphoursController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::group(['middleware' => ['auth']], function () {

    Route::resource('students', StudentController::class)->only(['index']); //users without the role teacher can only see the INDEX view

    Route::group(['middleware' => ['teacher']], function () { //users with the teacher role have acces to
        Route::resource('trainings', TrainingController::class)->except(['index','show']); //complete resource of trianings
        Route::resource('students', StudentController::class)->except(['index']); //complete resource of student

    });
    Route::resource('trainings', TrainingController::class)->only(['index','show']); //users without the role teacher can only see the INDEX view

    Route::resources([
        'hours' => HourController::class,
        'trainings.student' => TrainingStudentController::class,
        'internship_hours' => \App\Http\Controllers\InternshiphoursController::class,
        'teachers' => TeacherController::class,
        'companies' => \App\Http\Controllers\CompanyController::class,
        'KD' => KDController::class,
    ]);
    Route::get('school-company', [UserController::class, 'index'])->name('school.company');

    Route::get('show-hours', [HourController::class, 'show'])->name('hours.show');

    Route::get('/company/{company}/request', [InternshipController::class, 'request']);
    Route::get('/company/requests', [InternshipController::class, 'studentsRequests']);
    Route::post('/company/{company}/request', [InternshipController::class, 'requestPost']);

    Route::group(['prefix' => 'my-company'], function () {
        Route::get('requests', [InternshipController::class, 'requests']);
        //Todo:: improve these routes
        Route::get('requests/edit/{internship}', [InternshipController::class, 'edit']);
        Route::post('requests/edit/{internship}', [InternshipController::class, 'update']);
        Route::get('requests/deny/{internship}', [InternshipController::class, 'denyRequest']);
        Route::get('requests/accept/{internship}', [InternshipController::class, 'acceptRequest']);

        Route::get('stagaires', [InternshipController::class, 'stagaires']);
    });


    Route::get('create-company', [TeacherController::class, 'createcompanypage']);
    Route::get('change-company', [TeacherController::class, 'changecompanypage']);
    Route::get('change-hours{id}', [HourController::class, 'edit'])->name('change.hours');
    Route::get('delete-hours{id}', [HourController::class, 'destroy'])->name('delete.hours');
    Route::get('good-hours{id}', [InternshiphoursController::class, 'create'])->name('good.hours');
    Route::get('bad-hours{id}', [HourController::class, 'deny'])->name('bad.hours');
    Route::get('hours.update{id}', [HourController::class, 'update'])->name('hours.update');
    Route::get('created-company', [TeacherController::class, 'createcompany'])->name('create.company');
    Route::get('/changed-company{id}', [TeacherController::class, 'changecompany'])->name('change.company');
    Route::get('/delete-company/{id}', [TeacherController::class, 'deletecompany'])->name('delete.company');

    Route::get('/students/{student}/delete', [StudentController::class, 'delete']);
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/private/{file?}', 'FileController@get')->where('file', '(.*)');

    Route::get('/KD.showStudentKD', [App\Http\Controllers\KDController::class, 'showStudentKD']);

    Route::get('/profile', [App\Http\Controllers\ProfileController::class, 'show']);
    Route::post('/profile', [App\Http\Controllers\ProfileController::class, 'update']);

    Route::post('/update-password', [App\Http\Controllers\ProfileController::class, 'updatePassword']);
    Route::post('/send-mail', [App\Http\Controllers\MailController::class, 'store']);
    Route::post('/update-avatar', [App\Http\Controllers\ProfileController::class, 'updateAvatar']);
    Route::post('/update-adres', [App\Http\Controllers\ProfileController::class, 'updateAdres']);
});

app/Models/Training.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Training extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'title',
        'niveau',
        'sector',
        'leerweg',
        'duration',
        'description',
    ];

    static $roles = [
        0 => 'guest',
        1 => 'student',
        2 => 'bpv',
        3 => 'teacher'
    ];


    static $trajects = [
        'BOL',
        'BBL',
    ];


    static $rules = [
        'title' => 'required|max:255',
        'niveau' => 'required|int',
        'sector' => 'required|max:255',
        'leerweg' => 'required',
        'duration' => 'required|int',
        'description' => 'required'
        ];



    public function teachers()
    {
        return $this->belongsToMany(User::class)->wherePivot('user_role', '=', 3);
    }

    public function user()
    {
        return $this->belongsToMany(User::class);
    }


}

app/Http/Controllers/TrainingController.php
<?php

namespace App\Http\Controllers;

use App\Models\Training;
use App\Models\TrainingUser;
use App\Models\User;
use Illuminate\Http\Request;

class TrainingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $trainings = Training::where([
            ['title', '!=', null],
            [function ($query) use ($request) {
            if (($title = $request->title)) {
                $query->orWhere('title', 'LIKE', '%' . $title . '%')->get();
            }
            }]
        ])
            ->paginate(10);
        return view('trainings.index', compact('trainings'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Training $training)
    {
        return view('trainings.create',compact('training'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,Training $training)
    {
       $training = $training->create($request->validate(Training::$rules));

        TrainingUser::create( //connect training  to user that pressed on send button
            [
                'user_role' => 3,
                'training_id' => $training->id,
                'user_id' => auth()->user()->id
            ]);

        return redirect(route('trainings.index', [$training->id]));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Training  $training
     * @return \Illuminate\Http\Response
     */
    public function show(Training $training, User $user)
    {
        return view('trainings.show', compact('training','user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Training $training)
    {
        return view('trainings.edit',compact('training'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Training  $training
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Training $training)
    {
        $training->update($request->all());
        return redirect(route('trainings.index', [$training->id]));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Training  $training
     * @return \Illuminate\Http\Response
     */
    public function destroy(Training $training)
    {
        $training->delete();

        return redirect(route('trainings.index'));
    }
}

resources/views/trainings/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="yoo-uikits-heading">
            <h2 class="yoo-uikits-title">Nieuwe opleiding</h2>
        </div>
        <div class="yoo-height-b30 yoo-height-lg-b30"></div>
    </div>
    <form method="POST" action="{{route('trainings.store')}}">
        @csrf
        <div class="container">
            <div class="yoo-card yoo-style1">
                <div class="yoo-card-body">
                    <div class="row">
                        <div class="col-11">
                            <div class="yoo-height-b20 yoo-height-lg-b20"></div>


                            <div class="yoo-form-field-wrap yoo-style1">
                                <label class="yoo-form-field-label yoo-type1">Titel</label>
                                <div class="input-group form-group-sm">
                                    <input type="text" name="title" class="form-control" value="{{old('title')}}">
                                </div>
                            </div>

                            <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                            <div class="yoo-form-field-wrap yoo-style1">
                                <label class="yoo-form-field-label yoo-type1">Niveau</label>
                                <div class="input-group form-group-sm">
                                    <input type="number" name="niveau" class="form-control" value="{{old('niveau')}}">
                                </div>
                            </div>
                            <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                            <div class="yoo-form-field-wrap yoo-style1">
                                <label class="yoo-form-field-label yoo-type1">Sector</label>
                                <div class="input-group form-group-sm">
                                    <input type="text" name="sector" class="form-control" value="{{old('sector')}}">
                                </div>
                            </div>
                            <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                            <div class="yoo-form-field-wrap yoo-style1">
                                <label class="yoo-form-field-label yoo-type1">Leerweg</label>
                                <div class="yoo-select">
                                    <select class="form-control" id="exampleFormControlSelect1" name="leerweg">
                                        <option value="BOL" {{ old('leerweg') == 'BOL' ? 'selected' : '' }}>
                                            BOL
                                        </option>
                                        <option value="BBL" {{ old('leerweg') == 'BBL' ? 'selected' : '' }}>
                                            BBL
                                        </option>
                                    </select>
                                </div>
                            </div>
                            <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                            <div class="yoo-form-field-wrap yoo-style1">
                                <label class="yoo-form-field-label yoo-type1">Duur</label>
                                <div class="input-group form-group-sm">
                                    <input type="number" name="duration" class="form-control"
                                           value="{{old('duration')}}">
                                </div>
                            </div>
                            <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                            <div class="yoo-form-field-wrap yoo-style1">
                                <label class="yoo-form-field-label yoo-type1">Beschrijving</label>
                                <div class="input-group form-group-sm">
                            <textarea class="form-control" name="description" cols="30"
                                      rows="4">{{old('description')}}</textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                </div>
                @if(count($errors->all()))
                    @foreach ($errors->all() as $error)
                        <div class="row">
                            <div class="col-1"></div>
                            <div class="col-10">
                                <div class="alert alert-danger mt-2">
                                    {{$error}}
                                </div>
                            </div>
                            <div class="col-1"></div>
                        </div>
                    @endforeach
                @endif
                <hr>
                <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                <div class="yoo-profile-btn-group yoo-style1">
                    <button type="submit" class="yoo-profile-btn yoo-style1 yoo-color1">Opslaan
                    </button>
                </div>
                <div class="yoo-height-b20 yoo-height-lg-b20"></div>
            </div>
        </div>
    </form>

@endsection

resources/views/trainings/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="yoo-uikits-heading">
            <h2 class="yoo-uikits-title">Bewerk opleiding</h2>
        </div>
        <div class="yoo-height-b30 yoo-height-lg-b30"></div>
    </div>
    <form method="POST" action="{{route('trainings.update', $training->id) }}">
        <div class="container">
            <div class="yoo-card yoo-style1">
                <div class="yoo-card-body">
                    <div class="row">
                        <div class="col-11">
                            <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                            @csrf
                            @method('PUT')
                            <div class="yoo-form-field-wrap yoo-style1">
                                <label class="yoo-form-field-label yoo-type1">Titel</label>
                                <div class="input-group form-group-sm">
                                    <input type="text" name="title" class="form-control" value="{{$training->title}}">
                                </div>
                            </div>

                            <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                            <div class="yoo-form-field-wrap yoo-style1">
                                <label class="yoo-form-field-label yoo-type1">Niveau</label>
                                <div class="input-group form-group-sm">
                                    <input type="number" name="niveau" class="form-control" value="{{$training->niveau}}">
                                </div>
                            </div>
                            <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                            <div class="yoo-form-field-wrap yoo-style1">
                                <label class="yoo-form-field-label yoo-type1">Sector</label>
                                <div class="input-group form-group-sm">
                                    <input type="text" name="sector" class="form-control" value="{{$training->sector}}">
                                </div>
                            </div>
                            <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                            <div class="yoo-form-field-wrap yoo-style1">
                                <label class="yoo-form-field-label yoo-type1">Leerweg</label>
                                <div class="yoo-select">
                                    <select class="form-control" id="exampleFormControlSelect1" name="leerweg">
                                        <option value="BOL" {{ $training->leerweg == 'BOL' ? 'selected' : '' }}>
                                            BOL
                                        </option>
                                        <option value="BBL" {{ $training->leerweg == 'BBL' ? 'selected' : '' }}>
                                            BBL
                                        </option>
                                    </select>
                                </div>
                            </div>
                            <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                            <div class="yoo-form-field-wrap yoo-style1">
                                <label class="yoo-form-field-label yoo-type1">Duur</label>
                                <div class="input-group form-group-sm">
                                    <input type="number" name="duration" class="form-control"
                                           value="{{$training->duration}}">
                                </div>
                            </div>
                            <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                            <div class="yoo-form-field-wrap yoo-style1">
                                <label class="yoo-form-field-label yoo-type1">Beschrijving</label>
                                <div class="input-group form-group-sm">
                            <textarea class="form-control" name="description" cols="30"
                                      rows="4">{{$training->description}}</textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                </div>
                @if(count($errors->all()))
                    @foreach ($errors->all() as $error)
                        <div class="row">
                            <div class="col-1"></div>
                            <div class="col-10">
                                <div class="alert alert-danger mt-2">
                                    {{$error}}
                                </div>
                            </div>
                            <div class="col-1"></div>
                        </div>
                    @endforeach
                @endif
                <hr>
                <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                <div class="yoo-profile-btn-group yoo-style1">
                    <button type="submit" class="yoo-profile-btn yoo-style1 yoo-color1">Opslaan
                    </button>
                </div>
                <div class="yoo-height-b20 yoo-height-lg-b20"></div>
            </div>
        </div>
    </form>

@endsection

resources/views/trainings/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="yoo-uikits-heading d-flex justify-content-between">
            <h2 class="yoo-uikits-title">Opleidingen</h2>
        @if(Auth::user()->type == "teacher")
            <a class="btn btn-primary" href="{{ route('trainings.create') }}">Voeg een opleiding toe</a>
            @endif
        </div>
        <div class="yoo-height-b30 yoo-height-lg-b30"></div>
    </div>

    <div class="container">
        <div class="yoo-card yoo-style1">
            @if(count($trainings))
                <div class="yoo-card-body">
                    <div class="yoo-padd-lr-20">
                        <form action="{{ route('trainings.index') }}" method="GET" role="search">

                            <div class="input-group">
                                <input type="text" class="form-control mr-2 rounded" name="title" placeholder="Zoek opleiding" id="title">
                                <a href="{{ route('trainings.index') }}" class=" mt-1">
                                </a>

                            </div>

                        </form>

                        <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Titel</th>
                                <th>Duur</th>
                                <th>Niveau</th>
                                <th>Sector</th>
                                <th>Leerweg</th>
                                <th width="280px" class="text-right">Acties</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($trainings as $training)
                                <tr>
                                    <td>{{ $training->title }}</td>
                                    <td>{{ $training->duration }}</td>
                                    <td>{{ $training->niveau }}</td>
                                    <td>{{ $training->sector }}</td>
                                    <td>{{ $training->leerweg }}</td>
                                    <td class="text-right">
                                        <a href="/trainings/{{$training->id}}" class="btn btn-sm btn-info">
                                            <ion-icon class="text-white" name="eye-outline"></ion-icon>
                                        </a>


                                        <form action="/send-mail"
                                              style="display: unset"
                                              method="POST">
                                            @csrf

                                            <input type="hidden"
                                                   id="training"
                                                   name="training"
                                                   value="{{ $training->id }}"/>
                                            @if(Auth::user()->type == "student")
                                            <button type="submit" class="btn-sm btn-blue-gray btn-disabled" onclick="return confirm('Weet u zeker dat u deze email wilt sturen?')">
                                                <ion-icon class="text-white" name="mail-outline"></ion-icon>
                                            </button>
                                                @endif

                                        </form>
                                        @if(Auth::user()->type == "teacher")
                                            <button class="btn-sm btn-primary"

                                                    onclick="window.location.href = '{{ route('trainings.edit',$training->id) }}'">
                                            <ion-icon name="create-outline"></ion-icon>
                                        </button>

                                        <form action="{{ route('trainings.destroy',$training->id) }}"
                                              style="display: unset"
                                              method="POST">
                                            <button type="submit" class="btn-sm btn-danger">
                                                <ion-icon name="trash-outline"></ion-icon>
                                            </button>
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                    </div>
                </div>
                <hr>
                <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                <div class="yoo-profile-btn-group yoo-style1">
                    {!! $trainings->links() !!}
                </div>
            @else
                <div class="yoo-card-body">
                    <div class="yoo-padd-lr-20">
                        <div class="yoo-height-b20 yoo-height-lg-b20"></div>
                        Er zijn geen opleidingen gevonden.
                    </div>
                </div>
            @endif
        </div>
    </div>

@endsection

resources/views/trainings/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="yoo-uikits-heading d-flex justify-content-between">

            <h2 class="yoo-uikits-title">Opleiding {{$training->title}} </h2>
        </div>
        @if(Auth::user()->type == "teacher")
        <a class="btn btn-primary" href="{{ route('trainings.student.index', [$training->id]) }}">Voeg een student toe</a>
        @endif
        <div class="yoo-height-b30 yoo-height-lg-b30"></div>
    </div>

    <div class="container">
        <div class="yoo-card yoo-style1 ">
            <table class="table">
                <thead>
                <tr>
                    <th class="text-center pt-3"><h5>Opleiding informatie</h5></th>
                </tr>
                </thead>
            </table>

            <table>
                <tr>
                    <td class="px-5"> <h6 class="font-weight-light"> Naam: {{$training->title}}  </h6></td>
                </tr>
                <tr>
                    <td class="px-5"> <h6 class="font-weight-light"> Duur: {{$training->duration}}  </h6></td>
                </tr>
                <tr>
                    <td class="px-5"> <h6 class="font-weight-light"> Niveau: {{$training->niveau}}  </h6></td>
                </tr>
                <tr>
                    <td class="px-5"> <h6 class="font-weight-light"> Sector: {{$training->sector}}  </h6></td>
                </tr>
                <tr>
                    <td class="px-5"> <h6 class="font-weight-light"> Leerweg: {{$training->leerweg}}  </h6></td>
                </tr>
                <tr>
                    <td class="px-5"> <h6 class="font-weight-light"> Beschrijving: {{$training->description}}  </h6></td>
                </tr>

            </table>
        </div>
    </div>

@endsection